### ISSUE TITLE
Can not excute a payment

### ISSUE THREAD

**Issue by ivkean** [kyokomi/paypal#1]
This code maybe doesn't work, do you know why ?
```
client.Payment.Execute(paymentId, executeReq)
```
Because, i can not find any payments from:
```
/v1/payments/payment
```
Thank you :)

**Comment by kyokomi** [comment]
Your sandbox account is Non-US developers?

please read our [FAQ](https://developer.paypal.com/webapps/developer/docs/faq/#non-US-dev).

**Comment by ivkean** [comment]
But I can use Postman to request this excute url

**Comment by kyokomi** [comment]
This example can now see?

https://github.com/kyokomi/paypal/blob/master/example/main.go#L17-L61

**Comment by ivkean** [comment]
Thank you, i solved it.
